'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IValeES

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''imgLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lbl_Titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Titulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Formato1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Formato1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Formato2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Formato2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Formato3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Formato3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Unidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Placas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Placas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_TarComb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TarComb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_TarCirc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TarCirc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlacas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlacas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblTarComb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTarComb As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rblTarCirc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTarCirc As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_CondSalida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CondSalida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Fecha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_NoEco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_NoEco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Kms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Kms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Hora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Hora As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoEco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoEco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ExtLimp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ExtLimp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblExtLimp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblExtLimp As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_IntLimp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_IntLimp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblIntLimp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIntLimp As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_CondSalida2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CondSalida2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgVentoRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVentoRS As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgVentoLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVentoLS As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgSilveradoRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSilveradoRS As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgSilveradoLS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSilveradoLS As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgTanqueS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTanqueS As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lbl_DañosS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DañosS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblDaños1S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDaños1S As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rblDaños2S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDaños2S As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_OtrosS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_OtrosS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Conductor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Conductor1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Conductor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Conductor2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Vigilante1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Vigilante1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Vigilante2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Vigilante2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_RespUnidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RespUnidad1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_RespUnidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RespUnidad2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConductor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConductor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRespUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRespUnidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_CondEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CondEntrada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Fecha0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Fecha0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Hora0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Hora0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Kms0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Kms0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ExtLimp0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ExtLimp0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblExtLimp0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblExtLimp0 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_IntLimp0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_IntLimp0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblIntLimp0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIntLimp0 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_CondEntrada2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CondEntrada2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgVentoRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVentoRE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgVentoLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVentoLE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgSilveradoRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSilveradoRE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgSilveradoLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSilveradoLE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgTanqueE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTanqueE As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lbl_DañosE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DañosE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblDaños1E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDaños1E As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rblDaños2E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDaños2E As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lbl_OtrosE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_OtrosE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Entrega1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Entrega1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Entrega2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Entrega2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Vigilante3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Vigilante3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Vigilante4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Vigilante4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrega As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''_txtFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _txtFolio As Global.System.Web.UI.WebControls.TextBox
End Class
